#!/usr/bin/env python
import sys
import base64
import StringIO
k = StringIO.StringIO(base64.b64decode(sys.argv[1]))
k.read(1)
print('$pbkdf2-hmac-sha1$1000.'+k.read(16).encode('hex')+'.'+k.read(32).encode('hex'))
